/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TOBAKU.frame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dimas Fajar
 */
public class EditBarang extends javax.swing.JFrame {

    /**
     * Creates new form Edit
     */
    public EditBarang() {
        initComponents();
        try {
            ImageIcon barcodeIcon = new ImageIcon(input.barcodeImagePath);
 
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private String selectedBarangId;
    private String selectedSupplierId;
    private String selectedNama;
    private int selectedStok;
    private String selectedMerek;
    private String selectedKategori;
    private double selectedHargaJual;
    private double selectedHargaBeli;
    private String selectedSatuan;
    
    
    
    

    public void populateFields(String barangId, String supplierId, String nama, int stok, String merek,
            String kategori, double hargaJual, double hargaBeli, String satuan) {
        selectedBarangId = barangId;
        selectedSupplierId = supplierId;
        selectedNama = nama;
        selectedStok = stok;
        selectedMerek = merek;
        selectedKategori = kategori;
        selectedHargaJual = hargaJual;
        selectedHargaBeli = hargaBeli;
        selectedSatuan = satuan;

        // Mengisi kolom-kolom dengan data yang dipilih
        txtBarangID.setText(selectedBarangId);
        txtBarangID.setEditable(false);
        cbSupplier.setSelectedItem(selectedSupplierId);
        txtNamaBarang.setText(selectedNama);
        txtStok.setText(String.valueOf(selectedStok));
        txtMerek.setText(selectedMerek);
        cbKategori.setSelectedItem(selectedKategori);
        txtHargaJual.setText(String.valueOf(selectedHargaJual));
        txtHargaBeli.setText(String.valueOf(selectedHargaBeli));
        cbSatuan.setSelectedItem(selectedSatuan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tambahBarang = new javax.swing.JPanel();
        cbKategori = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        btnInBarang = new javax.swing.JButton();
        txtNamaBarang = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtHargaBeli = new javax.swing.JTextField();
        txtHargaJual = new javax.swing.JTextField();
        cbSatuan = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cbSupplier = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtMerek = new javax.swing.JTextField();
        txtBarangID = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        tambahBarang.setBackground(new java.awt.Color(240, 243, 252));
        tambahBarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbKategori.setForeground(new java.awt.Color(172, 177, 198));
        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bahan baku", "Alat memasak", "Kardus" }));
        tambahBarang.add(cbKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 150, 40));

        jLabel22.setText("Kategori");
        tambahBarang.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TOBAKU/icon/batal.png"))); // NOI18N
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        tambahBarang.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 550, 90, -1));

        btnInBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TOBAKU/icon/simpan.png"))); // NOI18N
        btnInBarang.setBorderPainted(false);
        btnInBarang.setContentAreaFilled(false);
        btnInBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInBarangActionPerformed(evt);
            }
        });
        tambahBarang.add(btnInBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 550, 88, -1));
        tambahBarang.add(txtNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 200, 40));
        tambahBarang.add(txtStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 200, 40));

        jLabel7.setText("Nama barang");
        tambahBarang.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        jLabel8.setText("Stok");
        tambahBarang.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, -1, -1));

        jLabel9.setText("Merek");
        tambahBarang.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));
        tambahBarang.add(txtHargaBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 220, 40));
        tambahBarang.add(txtHargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 250, 40));

        cbSatuan.setForeground(new java.awt.Color(172, 177, 198));
        cbSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kg", "ons", "pcs", "pack", "ball" }));
        tambahBarang.add(cbSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 330, 110, 40));

        jLabel10.setText("Satuan");
        tambahBarang.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, -1, -1));

        jLabel11.setText("Harga beli");
        tambahBarang.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, -1, -1));

        jLabel12.setText("Harga jual");
        tambahBarang.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setText("Edit Data Barang");
        tambahBarang.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        cbSupplier.setForeground(new java.awt.Color(172, 177, 198));
        cbSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cbSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSupplierActionPerformed(evt);
            }
        });
        tambahBarang.add(cbSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 160, 40));

        jLabel15.setText("Supplier");
        tambahBarang.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));
        tambahBarang.add(txtMerek, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 270, 40));
        tambahBarang.add(txtBarangID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 120, 40));

        jLabel17.setText("ID Barang");
        tambahBarang.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tambahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tambahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        txtMerek.setText("");
        cbSatuan.setSelectedIndex(0);
        cbKategori.setSelectedIndex(0);
        txtNamaBarang.setText("");
        txtStok.setText("");
        txtHargaJual.setText("");
        txtHargaBeli.setText("");
        cbSupplier.setSelectedIndex(0);
        dispose();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void btnInBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInBarangActionPerformed
        int supplierIndex = cbSupplier.getSelectedIndex();
        String supplierValue = cbSupplier.getSelectedItem().toString();
        String nama = txtNamaBarang.getText();
        String stok = txtStok.getText();
        String merek = txtMerek.getText();
        int kategoriIndex = cbKategori.getSelectedIndex();
        String kategoriValue = cbKategori.getSelectedItem().toString();
        String hargajual = txtHargaJual.getText();
        String hargabeli = txtHargaBeli.getText();
        int satuanIndex = cbSatuan.getSelectedIndex();
        String satuanValue = cbSatuan.getSelectedItem().toString();
        int barangId = Integer.parseInt(txtBarangID.getText());

        if (supplierIndex == -1 || nama.isEmpty() || stok.isEmpty() || merek.isEmpty()
                || kategoriIndex == -1 || hargajual.isEmpty() || hargabeli.isEmpty() || satuanIndex == -1) {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi semua field!");
            return;
        }

        String url = "jdbc:mysql://localhost:3306/tobakuu";
        String username = "root";
        String password = "";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, username, password);
            System.out.println("Berhasil terhubung ke database!");

            String query = "UPDATE barang SET SupplierID=?, Nama=?, Stok=?, Merek=?, Kategori=?, HargaJual=?, HargaBeli=?, Satuan=? WHERE BarangID=?";
            PreparedStatement statement = connection.prepareStatement(query);

            statement.setString(1, supplierValue);
            statement.setString(2, nama);
            statement.setString(3, stok);
            statement.setString(4, merek);
            statement.setString(5, kategoriValue);
            statement.setString(6, hargajual);
            statement.setString(7, hargabeli);
            statement.setString(8, satuanValue);
            statement.setInt(9, barangId);

            int rowsUpdated = statement.executeUpdate();
            if (rowsUpdated > 0) {
                System.out.println("Data berhasil diperbarui dalam database!");
                JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");
                cbSupplier.setSelectedIndex(-1);
                txtNamaBarang.setText("");
                txtStok.setText("");
                txtMerek.setText("");
                cbKategori.setSelectedIndex(-1);
                txtHargaJual.setText("");
                txtHargaBeli.setText("");
                cbSatuan.setSelectedIndex(-1);
                txtBarangID.setText("");
                dispose();
            }

            statement.close();
            connection.close();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Driver JDBC tidak ditemukan");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Koneksi error atau data yang dimasukkan tidak sesuai");
        } catch (Exception ex) {
            Logger.getLogger(input.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInBarangActionPerformed

    private void cbSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSupplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInBarang;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JComboBox<String> cbSatuan;
    private javax.swing.JComboBox<String> cbSupplier;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel tambahBarang;
    private javax.swing.JTextField txtBarangID;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtMerek;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
