/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TOBAKU.frame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Dimas Fajar
 */
public class EditPelanggan extends javax.swing.JFrame {

    /**
     * Creates new form EditPelanggan
     */
    public EditPelanggan() {
        initComponents();
    }

    private String selectedPelangganId;
    private String selectedJenisMember;
    private String selectedNamaPelanggan;
    private String selectedAlamat;
    private String selectedNomorHP;
    private String selectedEmailPelanggan;

    public void populateFields(String pelangganId, String jenisMember, String namaPelanggan, String alamat,
            String nomorHP, String emailPelanggan) {
        selectedPelangganId = pelangganId;
        selectedJenisMember = jenisMember;
        selectedNamaPelanggan = namaPelanggan;
        selectedAlamat = alamat;
        selectedNomorHP = nomorHP;
        selectedEmailPelanggan = emailPelanggan;

        // Mengisi kolom-kolom dengan data yang dipilih
        cbMember.setSelectedItem(selectedJenisMember);
        txtNamaPelanggan.setText(selectedNamaPelanggan);
        txtAlamat.setText(selectedAlamat);
        txtNoHP.setText(selectedNomorHP);
        txtEmail.setText(selectedEmailPelanggan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tambahPelanggan = new javax.swing.JPanel();
        cbMember = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        btnInPelanggan = new javax.swing.JButton();
        txtNamaPelanggan = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        txtNoHP = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        tambahPelanggan.setBackground(new java.awt.Color(240, 243, 252));
        tambahPelanggan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbMember.setForeground(new java.awt.Color(172, 177, 198));
        cbMember.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prioritas" }));
        tambahPelanggan.add(cbMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 250, 380, 40));

        jLabel14.setText("Jenis member");
        tambahPelanggan.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 220, -1, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TOBAKU/icon/batal.png"))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        tambahPelanggan.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 550, 90, -1));

        btnInPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TOBAKU/icon/simpan.png"))); // NOI18N
        btnInPelanggan.setBorderPainted(false);
        btnInPelanggan.setContentAreaFilled(false);
        btnInPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInPelangganActionPerformed(evt);
            }
        });
        tambahPelanggan.add(btnInPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 550, 88, -1));
        tambahPelanggan.add(txtNamaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 510, 40));

        jLabel23.setText("Nama pelanggan");
        tambahPelanggan.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));
        tambahPelanggan.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 360, 270, 40));
        tambahPelanggan.add(txtNoHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 300, 40));
        tambahPelanggan.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 310, 40));

        jLabel25.setText("Alamat");
        tambahPelanggan.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 330, -1, -1));

        jLabel26.setText("Nomor HP");
        tambahPelanggan.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        jLabel27.setText("Email");
        tambahPelanggan.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Masukkan Data Pelanggan");
        tambahPelanggan.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 998, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tambahPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tambahPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        cbMember.setSelectedIndex(0);
        txtNamaPelanggan.setText("");
        txtAlamat.setText("");
        txtEmail.setText("");
        txtNoHP.setText("");
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnInPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInPelangganActionPerformed
        String memberValue = cbMember.getSelectedItem().toString();
        String namaPelanggan = txtNamaPelanggan.getText();
        String alamat = txtAlamat.getText();
        String email = txtEmail.getText();
        String noHP = txtNoHP.getText();

        if (memberValue.isEmpty() || namaPelanggan.isEmpty() || alamat.isEmpty() || email.isEmpty() || noHP.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi semua field!");
            return;
        }

        String url = "jdbc:mysql://localhost:3306/tobakuu";
        String username = "root";
        String password = "";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, username, password);
            System.out.println("Berhasil terhubung ke database!");

            String query = "UPDATE pelanggan SET jenisMember=?, namaPelanggan=?, alamat=?, emailPelanggan=?, nomorHP=? WHERE pelangganID=?";
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setString(1, memberValue);
            statement.setString(2, namaPelanggan);
            statement.setString(3, alamat);
            statement.setString(4, email);
            statement.setString(5, noHP);
            statement.setString(6, selectedPelangganId); // Gunakan ID yang telah dipilih sebelumnya

            int rowsUpdated = statement.executeUpdate();
            if (rowsUpdated > 0) {
                System.out.println("Data berhasil diperbarui di dalam database!");
                JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");
                cbMember.setSelectedIndex(-1);
                txtNamaPelanggan.setText("");
                txtAlamat.setText("");
                txtEmail.setText("");
                txtNoHP.setText("");
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal memperbarui data.");
            }

            statement.close();
            connection.close();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Driver JDBC tidak ditemukan");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Koneksi error atau data yang dimasukkan tidak sesuai");
        }
    }//GEN-LAST:event_btnInPelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInPelanggan;
    private javax.swing.JComboBox<String> cbMember;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel tambahPelanggan;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtNoHP;
    // End of variables declaration//GEN-END:variables
}
