/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TOBAKU.frame;

import TOBAKU.koneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dimas Fajar
 */
public class overview extends javax.swing.JPanel {

    Connection conn = koneksi.getKoneksi();

    private ResultSet rs;
    private PreparedStatement pst;
    
    public overview() {
        initComponents();
        loadStokKurangTable();
    }

    private void loadStokKurangTable() {
        try {
            String sql = "SELECT * FROM barang_hampir_habis";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            // Membuat model tabel
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Nama");
            model.addColumn("Merek");
            model.addColumn("Stok");
            model.addColumn("Satuan");

            // Menambahkan data dari ResultSet ke dalam model tabel
            while (rs.next()) {
                String nama = rs.getString("Nama");
                String merek = rs.getString("merek");
                int stok = rs.getInt("Stok");
                String satuan = rs.getString("satuan");

                model.addRow(new Object[]{nama, merek, stok, satuan});
            }

            TabelStokKurang.setModel(model);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        label3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TabelStokKurang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(240, 243, 252));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label3.setBackground(new java.awt.Color(240, 243, 252));
        label3.setLayout(new java.awt.CardLayout());

        TabelStokKurang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(TabelStokKurang);

        label3.add(jScrollPane5, "card2");

        mainPanel.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 980, 430));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DATA BARANG HAMPIR HABIS");
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 680));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelStokKurang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel label3;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
