/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TOBAKU.frame;

import TOBAKU.koneksi.koneksi;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Dimas Fajar
 */
public class profil extends javax.swing.JPanel {

    Connection conn = koneksi.getKoneksi();

    /**
     * Creates new form profil
     */
    public profil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dashboardProfil = new javax.swing.JPanel();
        btnUpdateProfile = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNamaLengkap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmailOwner = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNoHpOwner = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTanggalLahir = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAlamatOwnwer = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        mainPanel.setBackground(new java.awt.Color(240, 243, 252));
        mainPanel.setLayout(new java.awt.CardLayout());

        dashboardProfil.setBackground(new java.awt.Color(240, 243, 252));
        dashboardProfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdateProfile.setBorderPainted(false);
        btnUpdateProfile.setContentAreaFilled(false);
        btnUpdateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProfileActionPerformed(evt);
            }
        });
        dashboardProfil.add(btnUpdateProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, 120, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(85, 85, 85));
        jLabel7.setText("Nama lengkap");
        dashboardProfil.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));
        dashboardProfil.add(txtNamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 430, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(85, 85, 85));
        jLabel4.setText("Sugeng Hariyadi");
        dashboardProfil.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));
        dashboardProfil.add(txtEmailOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 430, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(85, 85, 85));
        jLabel8.setText("Email");
        dashboardProfil.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, -1));
        dashboardProfil.add(txtNoHpOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 430, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(85, 85, 85));
        jLabel9.setText("Nomor HP");
        dashboardProfil.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));
        dashboardProfil.add(txtTanggalLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 430, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(85, 85, 85));
        jLabel10.setText("Tanggal lahir");
        dashboardProfil.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));
        dashboardProfil.add(txtAlamatOwnwer, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 430, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(85, 85, 85));
        jLabel11.setText("Alamat");
        dashboardProfil.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TOBAKU/icon/btn_Update.png"))); // NOI18N
        dashboardProfil.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(151, 151, 151));
        jLabel5.setText("Owner ToBaKu SIDOMULYO");
        dashboardProfil.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 210, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TOBAKU/icon/fotoAdmin.png"))); // NOI18N
        dashboardProfil.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TOBAKU/icon/assetProfil1.png"))); // NOI18N
        dashboardProfil.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TOBAKU/icon/assetprofil2.png"))); // NOI18N
        dashboardProfil.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 520, 610));

        mainPanel.add(dashboardProfil, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProfileActionPerformed
        String namaLengkap = txtNamaLengkap.getText();
        String emailOwner = txtEmailOwner.getText();
        String noHpOwner = txtNoHpOwner.getText();
        String tanggalLahir = txtTanggalLahir.getText();
        String alamatOwner = txtAlamatOwnwer.getText();

// Cek apakah field diisi dengan lengkap
        if (namaLengkap.isEmpty() || emailOwner.isEmpty() || noHpOwner.isEmpty()
                || tanggalLahir.isEmpty() || alamatOwner.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi semua field!");
            return;
        }

        String url = "jdbc:mysql://localhost:3306/tobakuu";
        String username = "root";
        String password = "";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, username, password);
            System.out.println("Berhasil terhubung ke database!");

            String query = "UPDATE user SET namaLengkap=?, email=?, nomor=?, tanggalLahir=?, alamat=? WHERE userID=?";
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setString(1, namaLengkap);
            statement.setString(2, emailOwner);
            statement.setString(3, noHpOwner);
            statement.setString(4, tanggalLahir);
            statement.setString(5, alamatOwner);
            statement.setInt(6, 4);

            int rowsUpdated = statement.executeUpdate();
            if (rowsUpdated > 0) {
                System.out.println("Data berhasil diperbarui di database!");
                JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");

                txtNamaLengkap.setText("");
                txtEmailOwner.setText("");
                txtNoHpOwner.setText("");
                txtTanggalLahir.setText("");
                txtAlamatOwnwer.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Gagal memperbarui data. Mohon periksa kembali User ID.");
            }

            statement.close();
            connection.close();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Driver JDBC tidak ditemukan");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Koneksi error");
        }

    }//GEN-LAST:event_btnUpdateProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateProfile;
    private javax.swing.JPanel dashboardProfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtAlamatOwnwer;
    private javax.swing.JTextField txtEmailOwner;
    private javax.swing.JTextField txtNamaLengkap;
    private javax.swing.JTextField txtNoHpOwner;
    private javax.swing.JTextField txtTanggalLahir;
    // End of variables declaration//GEN-END:variables
}
