/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TOBAKU.frame;

import TOBAKU.koneksi.koneksi;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dimas Fajar
 */
public class riwayat extends javax.swing.JPanel {

    Connection conn = koneksi.getKoneksi();

    /**
     * Creates new form riwayat
     */
    public riwayat() {
        initComponents();
        RiwayatPenjualan();
        RiwayatPembelian();
    }

    private void RiwayatPenjualan() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("JualID");
            model.addColumn("NamaPelanggan");
            model.addColumn("NamaBarang");
            model.addColumn("Jumlah");
            model.addColumn("Harga");
            model.addColumn("Total");
            model.addColumn("Bayar");
            model.addColumn("Diskon");
            model.addColumn("Tanggal");

            String query = "SELECT * FROM riwayat_penjualan";
            ResultSet rs = conn.createStatement().executeQuery(query);

            while (rs.next()) {
                String jualId = rs.getString("JualID");
                String namaPelanggan = rs.getString("NamaPelanggan");
                String namaBarang = rs.getString("NamaBarang");
                int jumlah = rs.getInt("Jumlah");
                double harga = rs.getDouble("Harga");
                double total = rs.getDouble("Total");
                double bayar = rs.getDouble("Bayar");
                double diskon = rs.getDouble("Diskon");
                Date tanggal = rs.getDate("Tanggal");

                model.addRow(new Object[]{jualId, namaPelanggan, namaBarang, jumlah, harga, total, bayar, diskon, tanggal});
            }

            tbPenjualan.setModel(model);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void RiwayatPembelian() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("BeliID");
            model.addColumn("NamaSupplier");
            model.addColumn("NamaBarang");
            model.addColumn("HargaSatuan");
            model.addColumn("Jumlah");
            model.addColumn("Total");
            model.addColumn("Bayar");
            model.addColumn("Subtotal");
            model.addColumn("Tanggal");

            String query = "SELECT BeliID, NamaSupplier, NamaBarang, HargaSatuan, Jumlah, Total, Bayar, subtotal, Tanggal FROM riwayat_pembelian";
            ResultSet rs = conn.createStatement().executeQuery(query);

            while (rs.next()) {
                String beliId = rs.getString("BeliID");
                String namaSupplier = rs.getString("NamaSupplier");
                String namaBarang = rs.getString("NamaBarang");
                double hargaSatuan = rs.getDouble("HargaSatuan");
                int jumlah = rs.getInt("Jumlah");
                double total = rs.getDouble("Total");
                double bayar = rs.getDouble("Bayar");
                double subtotal = rs.getDouble("Subtotal");
                Date tanggal = rs.getDate("Tanggal");

                model.addRow(new Object[]{beliId, namaSupplier, namaBarang, hargaSatuan, jumlah, total, bayar, subtotal, tanggal});
            }

            tbPembelian.setModel(model);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dashboardRiwayat = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        riwayatPembelian = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        labelTB1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbPembelian = new javax.swing.JTable();
        riwayatPenjualan = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        labelTB = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbPenjualan = new javax.swing.JTable();

        mainPanel.setBackground(new java.awt.Color(240, 243, 252));
        mainPanel.setLayout(new java.awt.CardLayout());

        dashboardRiwayat.setBackground(new java.awt.Color(240, 243, 252));
        dashboardRiwayat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Riwayat Pembelian");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        dashboardRiwayat.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 380, 60));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Riwayat Penjualan");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        dashboardRiwayat.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 390, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TOBAKU/icon/btn_panjang.png"))); // NOI18N
        dashboardRiwayat.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TOBAKU/icon/btn_panjang.png"))); // NOI18N
        dashboardRiwayat.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TOBAKU/icon/datapenjualan.png"))); // NOI18N
        dashboardRiwayat.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TOBAKU/icon/datapembelian.png"))); // NOI18N
        dashboardRiwayat.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Riwayat Penjualan dan Pembelian");
        dashboardRiwayat.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        mainPanel.add(dashboardRiwayat, "card2");

        riwayatPembelian.setBackground(new java.awt.Color(240, 243, 252));
        riwayatPembelian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Cari Riwayat Pembelian");
        riwayatPembelian.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TOBAKU/icon/back.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        riwayatPembelian.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 40, -1));

        labelTB1.setBackground(new java.awt.Color(240, 243, 252));
        labelTB1.setLayout(new java.awt.CardLayout());

        tbPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tbPembelian);

        labelTB1.add(jScrollPane6, "card2");

        riwayatPembelian.add(labelTB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 980, 480));

        mainPanel.add(riwayatPembelian, "card2");

        riwayatPenjualan.setBackground(new java.awt.Color(240, 243, 252));
        riwayatPenjualan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Cari Riwayat Penjualan");
        riwayatPenjualan.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TOBAKU/icon/back.png"))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        riwayatPenjualan.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 40, -1));

        labelTB.setBackground(new java.awt.Color(240, 243, 252));
        labelTB.setLayout(new java.awt.CardLayout());

        tbPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tbPenjualan);

        labelTB.add(jScrollPane5, "card2");

        riwayatPenjualan.add(labelTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 980, 480));

        mainPanel.add(riwayatPenjualan, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        mainPanel.removeAll();
        mainPanel.add(dashboardRiwayat);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(riwayatPembelian);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(riwayatPenjualan);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        mainPanel.removeAll();
        mainPanel.add(dashboardRiwayat);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dashboardRiwayat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel labelTB;
    private javax.swing.JPanel labelTB1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel riwayatPembelian;
    private javax.swing.JPanel riwayatPenjualan;
    private javax.swing.JTable tbPembelian;
    private javax.swing.JTable tbPenjualan;
    // End of variables declaration//GEN-END:variables
}
