package TOBAKU.main;

import TOBAKU.koneksi.koneksi;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Dimas Fajar
 */
public class lupaPs extends javax.swing.JFrame {

    Connection conn = koneksi.getKoneksi();

    /**
     * Creates new form lupaPs
     */
    public lupaPs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        username1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hobby1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Newpassword1 = new javax.swing.JTextField();
        loginbr1 = new javax.swing.JButton();
        update1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1090, 630));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1090, 630));

        jPanel3.setBackground(new java.awt.Color(212, 231, 252));
        jPanel3.setPreferredSize(new java.awt.Dimension(641, 717));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TOBAKU/icon/exit.png"))); // NOI18N
        jButton2.setToolTipText("");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, 33, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Lupa Password");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TOBAKU/icon/Vectors.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Username/Email");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        username1.setBackground(new java.awt.Color(34, 73, 87));
        username1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username1.setForeground(new java.awt.Color(255, 255, 255));
        username1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 340, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Konfirmasi Hobi");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        hobby1.setBackground(new java.awt.Color(34, 73, 87));
        hobby1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hobby1.setForeground(new java.awt.Color(255, 255, 255));
        hobby1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(hobby1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 340, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Password Baru");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        Newpassword1.setBackground(new java.awt.Color(34, 73, 87));
        Newpassword1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Newpassword1.setForeground(new java.awt.Color(255, 255, 255));
        Newpassword1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Newpassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Newpassword1ActionPerformed(evt);
            }
        });
        jPanel3.add(Newpassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 340, 40));

        loginbr1.setBackground(new java.awt.Color(240, 230, 252));
        loginbr1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginbr1.setText("Login?");
        loginbr1.setBorder(new javax.swing.border.MatteBorder(null));
        loginbr1.setBorderPainted(false);
        loginbr1.setContentAreaFilled(false);
        loginbr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbr1ActionPerformed(evt);
            }
        });
        jPanel3.add(loginbr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        update1.setBackground(new java.awt.Color(116, 152, 207));
        update1.setForeground(new java.awt.Color(255, 255, 255));
        update1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TOBAKU/icon/Update btn.png"))); // NOI18N
        update1.setBorder(null);
        update1.setBorderPainted(false);
        update1.setContentAreaFilled(false);
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });
        jPanel3.add(update1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Newpassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Newpassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Newpassword1ActionPerformed

    private void loginbr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbr1ActionPerformed
        login lg = new login();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_loginbr1ActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        String usernameText = username1.getText();
        String newPsText = Newpassword1.getText();
        String hobbyText = hobby1.getText();

        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/tobakuu", "root", "");
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM user WHERE userName='" + usernameText + "' AND hobby='" + hobbyText + "'")) {

            if (rs.next()) {
                st.executeUpdate("UPDATE user SET password='" + newPsText + "' WHERE username='" + usernameText + "' AND hobby='" + hobbyText + "'");
                JOptionPane.showMessageDialog(null, "Berhasil mengganti password");
                setVisible(false);
                new login().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Tolong tuliskan username atau hobby yang benar");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Koneksi error");
        }
    }//GEN-LAST:event_update1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lupaPs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lupaPs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lupaPs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lupaPs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lupaPs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Newpassword1;
    private javax.swing.JTextField hobby1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginbr1;
    private javax.swing.JButton update1;
    private javax.swing.JTextField username1;
    // End of variables declaration//GEN-END:variables
}
